version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: agendaapi_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: agendaapi_db
      POSTGRES_USER: agenda_user
      POSTGRES_PASSWORD: agenda_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agendaapi_network

volumes:
  postgres_data:

networks:
  agendaapi_network:
    driver: bridge
